v1.0.4 Added -o, $HOSTNAME->$MULTXHOST, use stdin/out, cosmetic changes

diff --git a/multx/multx b/multx/multx
--- a/multx/multx
+++ b/multx/multx
@@ -40,7 +40,7 @@
 # This script is a template. That is, it will almost certainly be more useful if
 # it's modified to suit your particular environment.
 ################################################################################
-VERSION=1.0.3
+VERSION=1.0.4
 PROG=$(basename $0)
 
 ######### Define hostname group(s) and options
@@ -49,39 +49,41 @@ HOST_GROUP_R="barney betty"		# Rubbles
 HOST_GROUP_K="pebbles bamm-bamm"	# Kids
 HOST_GROUP_a="$HOST_GROUP_F $HOST_GROUP_R $HOST_GROUP_K"
 
-CONFIRMFLAG=0
+USERCONFIRMATIONFLAG=0
 BACKGROUNDFLAG=0
 QUIETFLAG=0
+LOCALEXECUTIONFLAG=0
 SSHARGS=""
-HOSTNAMES=""
-OUTFILEPAT=""
+TARGETHOSTS=""
+OUTPUTFILENAMETEMPLATE=""
 
-OPTIONS="FRKabch:f:o:qs:x:"
+OPTIONS="FRKabch:f:lo:qs:x:"
 while getopts "$OPTIONS" OPTION; do
     case $OPTION in
-	F) HOSTNAMES="$HOSTNAMES $HOST_GROUP_F";;
-	R) HOSTNAMES="$HOSTNAMES $HOST_GROUP_R";;
-	K) HOSTNAMES="$HOSTNAMES $HOST_GROUP_K";;
-	a) HOSTNAMES="$HOSTNAMES $HOST_GROUP_a";;
+	F) TARGETHOSTS="$TARGETHOSTS $HOST_GROUP_F";;
+	R) TARGETHOSTS="$TARGETHOSTS $HOST_GROUP_R";;
+	K) TARGETHOSTS="$TARGETHOSTS $HOST_GROUP_K";;
+	a) TARGETHOSTS="$TARGETHOSTS $HOST_GROUP_a";;
 	b) BACKGROUNDFLAG=1;;
-	c) CONFIRMFLAG=1;;
-	h) HOSTNAMES="$HOSTNAMES $OPTARG";;
+	c) USERCONFIRMATIONFLAG=1;;
+	h) TARGETHOSTS="$TARGETHOSTS $OPTARG";;
 	f)  if [ -r $OPTARG ]; then
-		HOSTNAMES="$HOSTNAMES $(cat $OPTARG)"
+		TARGETHOSTS="$TARGETHOSTS $(cat $OPTARG)"
 	    else
 		echo "$PROG: cannot read file '$OPTARG'"
 	    fi;;
-	o) OUTFILEPAT="$OPTARG";;
+	l) LOCALEXECUTIONFLAG=1;;
+	o) OUTPUTFILENAMETEMPLATE="$OPTARG";;
 	q) QUIETFLAG=1;;
 	s) SSHARGS="$SSHARGS $OPTARG";;
-	x) HOSTNAMES=$(echo "$HOSTNAMES" | awk -v optarg="$OPTARG" '{gsub(optarg, ""); print $0}');;
+	x) TARGETHOSTS=$(echo "$TARGETHOSTS" | awk -v optarg="$OPTARG" '{gsub(optarg, ""); print $0}');;
     esac
 done
 shift $((OPTIND-1))
 
-CMD=$*
+RUNCOMMAND=$*
 
-if [ "$CMD" == "" ]; then
+if [ "$RUNCOMMAND" == "" ]; then
     echo "usage (version $VERSION):
 $PROG [option(s)] remote_command
   Where options are: $OPTIONS
@@ -93,50 +95,75 @@ $PROG [option(s)] remote_command
     -c			:  confirmation mode
     -h host_list	:+ add a hostname or 'hostname_1 ... hostname_n'
     -f file		:+ read a file containing hostname(s)
-    -o outfilepat	:  output file pattern (\"'\${HOSTNAME}.info'\" is a useful choice)
+    -l                  :  execute the command on the local (initiating) host
+                           e.g.: multx -al 'scp /etc/hosts \${MULTXTARGET}:/tmp'
+    -o outfilepat	:  output file pattern (\"'\${MULTXTARGET}.info'\" is a useful choice)
     -q			:  quiet mode
     -s ssh_arg(s)	:+ arguments to be passed to ssh
     -x ERE		:+ eXclude all/part of hostname(s) containing this ERE (pattern)
     '+' options may be used more than once and/or combined with others
+    Note: \$MT works the same as \$MULTXTARGET.
 multx Copyright (C) 2016-2023 James S. Crook
 This program comes with ABSOLUTELY NO WARRANTY and is distributed under the FreeBSD license."
-    exit
+    exit 0
 fi
 
-if [ $CONFIRMFLAG -ne 0 ]; then
-    printf "execute <ssh $SSHARGS $CMD> on <$(echo $HOSTNAMES)> (y/n)?" > /dev/tty
-    read REPLY < /dev/tty
+if [ "$TARGETHOSTS" == "" ]; then
+    echo "[E: *** No hostnames have been specified, aborting. ***]"
+    exit 1
+fi
+
+if [ $LOCALEXECUTIONFLAG -ne 0 -a \( "$OUTPUTFILENAMETEMPLATE" != "" -o "$SSHARGS" != "" \) ]; then
+    echo "[W: *** When '-l' is used, both the '-o' and '-s' options are ignored. ***]"
+fi
+
+if [ $USERCONFIRMATIONFLAG -ne 0 ]; then
+    printf "Execute <ssh $SSHARGS $RUNCOMMAND> on <$(echo $TARGETHOSTS)> (y/n)?"
+    read USERREPLY
+    LOWERCASEUSERREPLY=$(echo $USERREPLY | tr A-Z a-z)
+    case $LOWERCASEUSERREPLY in
+	y|yes)	LOWERCASEUSERREPLY="y";;
+	*)	LOWERCASEUSERREPLY="n";;
+    esac
 else
-    REPLY="y"
+    LOWERCASEUSERREPLY="y"
 fi
 
-if [ "$REPLY" == "y" -o "$REPLY" = "Y" ]; then
-    echo "$(date) : $PROG starting"
-    for HOSTNAME in $HOSTNAMES; do
-	if [ $QUIETFLAG -eq 0 ]; then echo "$HOSTNAME === <$CMD> ==="; fi
+if [ "$LOWERCASEUSERREPLY" == "y" ]; then
+    echo "[i: $(date) : $PROG begin]"
+    for MULTXTARGET in $TARGETHOSTS; do
+	MT=$MULTXTARGET			# so $MT and $MULTXTARGET will both work!
+	if [ $QUIETFLAG -eq 0 ]; then echo "[i: $MULTXTARGET === <$RUNCOMMAND> ===]"; fi
 
-	if [ "$OUTFILEPAT" == "" ]; then
-	    if [ $BACKGROUNDFLAG -eq 0 ]; then
-		ssh $SSHARGS $HOSTNAME "$CMD"
+	if [ $LOCALEXECUTIONFLAG -eq 0 ]; then
+	    if [ "$OUTPUTFILENAMETEMPLATE" == "" ]; then
+		if [ $BACKGROUNDFLAG -eq 0 ]; then
+		    ssh $SSHARGS $MULTXTARGET "$RUNCOMMAND"
+		else
+		    ssh $SSHARGS $MULTXTARGET "$RUNCOMMAND" &
+		fi
 	    else
-		ssh $SSHARGS $HOSTNAME "$CMD" &
+		LOCOUTFILE=$(eval echo $OUTPUTFILENAMETEMPLATE)
+		if [ $BACKGROUNDFLAG -eq 0 ]; then
+		    ssh $SSHARGS $MULTXTARGET "$RUNCOMMAND" > "$LOCOUTFILE"
+		else
+		    ssh $SSHARGS $MULTXTARGET "$RUNCOMMAND" > "$LOCOUTFILE" &
+		fi
 	    fi
 	else
-	    H=$HOSTNAME			# so $H and $HOSTNAME will both work!
-	    LOCOUTFILE=$(eval echo $OUTFILEPAT)
 	    if [ $BACKGROUNDFLAG -eq 0 ]; then
-		ssh $SSHARGS $HOSTNAME "$CMD" > "$LOCOUTFILE"
+		eval "$RUNCOMMAND"
 	    else
-		ssh $SSHARGS $HOSTNAME "$CMD" > "$LOCOUTFILE" &
+		eval "$RUNCOMMAND" &
 	    fi
 	fi
 
 	if [ $QUIETFLAG -eq 0 ]; then echo; fi
     done
     wait	# No effect in foreground mode
-    echo "$(date) : $PROG finished"
+    echo "[i: $(date) : $PROG end]"
 else
-    echo "$PROG exiting"
+    echo "[i: $PROG exiting]"
 fi
 
 exit 0
